### ISSUE TITLE
Niedziałający Licznik

### ISSUE THREAD

**Issue by friz666** [Nowak0/SilenceStudio2#1]
Nie działa licznik, a powinien. Trzeba to zweryfikować. Wyjściowy wygląd (i działający przy okazji) znajduje się na moim replu: replit.com/@Kubaa/stronatest\
dzieki

**Comment by friz666** [comment]
Haha, żartowałem. To  sie samo naprawiło.. Znaczy to ja rozwiązałem ten problem. Co za dominacja genetyczna.

**Comment by Nowak0** [comment]
Dobrze, że problem zażegnany. Czasami wystarczy kilka kliknięć i już działa. Zaraz spojrzę na efekty. #GettingJobDone #MyTop #OZK
